security:
    firewalls:
        apparels_webservice:
                pattern: ^/webservice
                stateless: true
                provider: pimcore_admin
                guard:
                    authenticators:
                        - EventBundle\Security\Guard\WebserviceAuthenticator
